[package]
name = "yscrdt"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "yscrdt"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
bincode = "1.3"
serde = { version = "1.0.209", features = ["derive"] }
yrs = "0.21.0"
